# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_tenable_io_assets"""

try:
    from resilient import ImportDefinition
except ImportError:
    # Support Apps running on resilient-circuits < v35.0.195
    from resilient_circuits.util import ImportDefinition


def codegen_reload_data():
    """
    Parameters required reload codegen for the fn_tenable_io_assets package
    """
    return {
        "package": u"fn_tenable_io_assets",
        "message_destinations": [u"fn_tio_assets"],
        "functions": [u"tenable_io_assets"],
        "workflows": [],
        "actions": [],
        "incident_fields": [],
        "incident_artifact_types": [],
        "datatables": [],
        "automatic_tasks": [],
        "scripts": []
    }


def customization_data(client=None):
    """
    Returns a Generator of ImportDefinitions (Customizations).
    Install them using `resilient-circuits customize`

    Contents:
    - Message Destinations:
        - fn_tio_assets
    - Functions:
        - tenable_io_assets
    """

    yield ImportDefinition(u"""
eyJhY3Rpb25fb3JkZXIiOiBbXSwgImFjdGlvbnMiOiBbXSwgImFwcHMiOiBbXSwgImF1dG9tYXRp
Y190YXNrcyI6IFtdLCAiZXhwb3J0X2RhdGUiOiAxNjAyNjQ1NDI3NjIzLCAiZXhwb3J0X2Zvcm1h
dF92ZXJzaW9uIjogMiwgImZpZWxkcyI6IFt7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwg
ImJsYW5rX29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6
IHRydWUsICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNl
LCAiZGVwcmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJfX2Z1bmN0aW9uL2FydGlmYWN0
X2lkIiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDE5NSwgImlucHV0X3R5cGUi
OiAibnVtYmVyIiwgImludGVybmFsIjogZmFsc2UsICJpc190cmFja2VkIjogZmFsc2UsICJuYW1l
IjogImFydGlmYWN0X2lkIiwgIm9wZXJhdGlvbl9wZXJtcyI6IHt9LCAib3BlcmF0aW9ucyI6IFtd
LCAicGxhY2Vob2xkZXIiOiAiIiwgInByZWZpeCI6IG51bGwsICJyZWFkX29ubHkiOiBmYWxzZSwg
InJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6IFt7InRhZ19oYW5kbGUiOiAiZm5fdmlydXN0b3Rh
bCIsICJ2YWx1ZSI6IG51bGx9XSwgInRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJhcnRpZmFjdF9p
ZCIsICJ0b29sdGlwIjogIiIsICJ0eXBlX2lkIjogMTEsICJ1dWlkIjogImQ4YzMwM2VlLTlhYzkt
NGQwNi04ZTE4LTJmY2FmMmMxYTZiNiIsICJ2YWx1ZXMiOiBbXX0sIHsiYWxsb3dfZGVmYXVsdF92
YWx1ZSI6IGZhbHNlLCAiYmxhbmtfb3B0aW9uIjogZmFsc2UsICJjYWxjdWxhdGVkIjogZmFsc2Us
ICJjaGFuZ2VhYmxlIjogdHJ1ZSwgImNob3NlbiI6IGZhbHNlLCAiZGVmYXVsdF9jaG9zZW5fYnlf
c2VydmVyIjogZmFsc2UsICJkZXByZWNhdGVkIjogZmFsc2UsICJleHBvcnRfa2V5IjogIl9fZnVu
Y3Rpb24vdGlvX29wZXJhdGlvbl90eXBlIiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJp
ZCI6IDI1NywgImlucHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNlLCAiaXNfdHJh
Y2tlZCI6IGZhbHNlLCAibmFtZSI6ICJ0aW9fb3BlcmF0aW9uX3R5cGUiLCAib3BlcmF0aW9uX3Bl
cm1zIjoge30sICJvcGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4Ijog
bnVsbCwgInJlYWRfb25seSI6IGZhbHNlLCAicmljaF90ZXh0IjogZmFsc2UsICJ0YWdzIjogW10s
ICJ0ZW1wbGF0ZXMiOiBbXSwgInRleHQiOiAidGlvX29wZXJhdGlvbl90eXBlIiwgInRvb2x0aXAi
OiAiVGVuYWJsZS5pbyBPcGVyYXRpb24gc3VjaCBhcyBsb29rdXAgYW5kIHNjYW4uIiwgInR5cGVf
aWQiOiAxMSwgInV1aWQiOiAiZGVkZjBhYWUtZmNlMi00NzIwLWI5NWEtOTkyYWRhOWU3NGEzIiwg
InZhbHVlcyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjogZmFsc2UsICJibGFua19vcHRp
b24iOiBmYWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5nZWFibGUiOiB0cnVlLCAiY2hv
c2VuIjogZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwgImRlcHJlY2F0
ZWQiOiBmYWxzZSwgImV4cG9ydF9rZXkiOiAiX19mdW5jdGlvbi90aW9fb3BlcmF0aW9uX3BhcmFt
MSIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAyNTgsICJpbnB1dF90eXBlIjog
InRleHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwgIm5hbWUiOiAi
dGlvX29wZXJhdGlvbl9wYXJhbTEiLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJvcGVyYXRpb25z
IjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogbnVsbCwgInJlYWRfb25seSI6IGZh
bHNlLCAicmljaF90ZXh0IjogZmFsc2UsICJ0YWdzIjogW10sICJ0ZW1wbGF0ZXMiOiBbXSwgInRl
eHQiOiAidGlvX29wZXJhdGlvbl9wYXJhbTEiLCAidG9vbHRpcCI6ICJUaGUgcGFyYW1ldGVyIGZv
ciBUZW5hYmxlLmlvIG9wZXJhdGlvbiBzdWNoIGFzIElQIGFkZHJlc3MoZXMpIiwgInR5cGVfaWQi
OiAxMSwgInV1aWQiOiAiZmFjYzRjOWMtY2M5NC00MWYxLTgwNDQtOWE2OTQ3ZGQ5Y2FkIiwgInZh
bHVlcyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjogZmFsc2UsICJibGFua19vcHRpb24i
OiBmYWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5nZWFibGUiOiB0cnVlLCAiY2hvc2Vu
IjogZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwgImRlcHJlY2F0ZWQi
OiBmYWxzZSwgImV4cG9ydF9rZXkiOiAiX19mdW5jdGlvbi90aW9fb3BlcmF0aW9uX3BhcmFtMiIs
ICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAyNTksICJpbnB1dF90eXBlIjogInRl
eHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwgIm5hbWUiOiAidGlv
X29wZXJhdGlvbl9wYXJhbTIiLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJvcGVyYXRpb25zIjog
W10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogbnVsbCwgInJlYWRfb25seSI6IGZhbHNl
LCAicmljaF90ZXh0IjogZmFsc2UsICJ0YWdzIjogW10sICJ0ZW1wbGF0ZXMiOiBbXSwgInRleHQi
OiAidGlvX29wZXJhdGlvbl9wYXJhbTIiLCAidG9vbHRpcCI6ICJUaGUgcGFyYW1ldGVyIGZvciBU
ZW5hYmxlLmlvIG9wZXJhdGlvbiBzdWNoIGFzIElQIGFkZHJlc3MoZXMpIiwgInR5cGVfaWQiOiAx
MSwgInV1aWQiOiAiMjA2NGI2ZmItZjRiZi00MzUwLWI3OTgtNTk0ZjQzZjAyNDRjIiwgInZhbHVl
cyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjogZmFsc2UsICJibGFua19vcHRpb24iOiBm
YWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5nZWFibGUiOiB0cnVlLCAiY2hvc2VuIjog
ZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwgImRlcHJlY2F0ZWQiOiBm
YWxzZSwgImV4cG9ydF9rZXkiOiAiX19mdW5jdGlvbi9pbmNpZGVudF9pZCIsICJoaWRlX25vdGlm
aWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAxOTQsICJpbnB1dF90eXBlIjogIm51bWJlciIsICJpbnRl
cm5hbCI6IGZhbHNlLCAiaXNfdHJhY2tlZCI6IGZhbHNlLCAibmFtZSI6ICJpbmNpZGVudF9pZCIs
ICJvcGVyYXRpb25fcGVybXMiOiB7fSwgIm9wZXJhdGlvbnMiOiBbXSwgInBsYWNlaG9sZGVyIjog
IiIsICJwcmVmaXgiOiBudWxsLCAicmVhZF9vbmx5IjogZmFsc2UsICJyZXF1aXJlZCI6ICJhbHdh
eXMiLCAicmljaF90ZXh0IjogZmFsc2UsICJ0YWdzIjogW3sidGFnX2hhbmRsZSI6ICJmbl92aXJ1
c3RvdGFsIiwgInZhbHVlIjogbnVsbH1dLCAidGVtcGxhdGVzIjogW10sICJ0ZXh0IjogImluY2lk
ZW50X2lkIiwgInRvb2x0aXAiOiAiIiwgInR5cGVfaWQiOiAxMSwgInV1aWQiOiAiNTA5ZDZiNTgt
ZTRiNS00MTUwLWIxZDAtNjg0M2M2ZGNmYjhkIiwgInZhbHVlcyI6IFtdfSwgeyJleHBvcnRfa2V5
IjogImluY2lkZW50L2ludGVybmFsX2N1c3RvbWl6YXRpb25zX2ZpZWxkIiwgImlkIjogMCwgImlu
cHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IHRydWUsICJuYW1lIjogImludGVybmFsX2N1
c3RvbWl6YXRpb25zX2ZpZWxkIiwgInJlYWRfb25seSI6IHRydWUsICJ0ZXh0IjogIkN1c3RvbWl6
YXRpb25zIEZpZWxkIChpbnRlcm5hbCkiLCAidHlwZV9pZCI6IDAsICJ1dWlkIjogImJmZWVjMmQ0
LTM3NzAtMTFlOC1hZDM5LTRhMDAwNDA0NGFhMSJ9XSwgImZ1bmN0aW9ucyI6IFt7ImNyZWF0b3Ii
OiB7ImRpc3BsYXlfbmFtZSI6ICJSZXNpbGllbnQgU3lzYWRtaW4iLCAiaWQiOiAxLCAibmFtZSI6
ICJyZXNhZG1pbkBsb2NhbC5jb20iLCAidHlwZSI6ICJ1c2VyIn0sICJkZXNjcmlwdGlvbiI6IHsi
Zm9ybWF0IjogInRleHQiLCAiY29udGVudCI6ICJGdW5jdGlvbiBmb3IgbXVsdGlwbGUgb3BlcmF0
aW9uczpcbi0gR2V0cyBBc3NldCBkYXRhIGZyb20gVGVuYWJsZS5pby5cbi0gSW52b2tlIFRlbmFi
bGUuaW8gVnVsbmVyYWJpbGl0eSBzY2FuIGZvciB0aGUgQXNzZXQocykuIn0sICJkZXN0aW5hdGlv
bl9oYW5kbGUiOiAiZm5fdGlvX2Fzc2V0cyIsICJkaXNwbGF5X25hbWUiOiAiVGVuYWJsZS5pbyBB
c3NldHMiLCAiZXhwb3J0X2tleSI6ICJ0ZW5hYmxlX2lvX2Fzc2V0cyIsICJpZCI6IDExLCAibGFz
dF9tb2RpZmllZF9ieSI6IHsiZGlzcGxheV9uYW1lIjogIlJlc2lsaWVudCBTeXNhZG1pbiIsICJp
ZCI6IDEsICJuYW1lIjogInJlc2FkbWluQGxvY2FsLmNvbSIsICJ0eXBlIjogInVzZXIifSwgImxh
c3RfbW9kaWZpZWRfdGltZSI6IDE2MDI2NDUyMzc0MTQsICJuYW1lIjogInRlbmFibGVfaW9fYXNz
ZXRzIiwgInRhZ3MiOiBbXSwgInV1aWQiOiAiYzg3N2M4ZGEtMmQ3Yy00YzQxLWJlNjctYzAwMzIy
NmNhNTNlIiwgInZlcnNpb24iOiAzLCAidmlld19pdGVtcyI6IFt7ImNvbnRlbnQiOiAiNTA5ZDZi
NTgtZTRiNS00MTUwLWIxZDAtNjg0M2M2ZGNmYjhkIiwgImVsZW1lbnQiOiAiZmllbGRfdXVpZCIs
ICJmaWVsZF90eXBlIjogIl9fZnVuY3Rpb24iLCAic2hvd19pZiI6IG51bGwsICJzaG93X2xpbmtf
aGVhZGVyIjogZmFsc2UsICJzdGVwX2xhYmVsIjogbnVsbH0sIHsiY29udGVudCI6ICJkOGMzMDNl
ZS05YWM5LTRkMDYtOGUxOC0yZmNhZjJjMWE2YjYiLCAiZWxlbWVudCI6ICJmaWVsZF91dWlkIiwg
ImZpZWxkX3R5cGUiOiAiX19mdW5jdGlvbiIsICJzaG93X2lmIjogbnVsbCwgInNob3dfbGlua19o
ZWFkZXIiOiBmYWxzZSwgInN0ZXBfbGFiZWwiOiBudWxsfSwgeyJjb250ZW50IjogImRlZGYwYWFl
LWZjZTItNDcyMC1iOTVhLTk5MmFkYTllNzRhMyIsICJlbGVtZW50IjogImZpZWxkX3V1aWQiLCAi
ZmllbGRfdHlwZSI6ICJfX2Z1bmN0aW9uIiwgInNob3dfaWYiOiBudWxsLCAic2hvd19saW5rX2hl
YWRlciI6IGZhbHNlLCAic3RlcF9sYWJlbCI6IG51bGx9LCB7ImNvbnRlbnQiOiAiZmFjYzRjOWMt
Y2M5NC00MWYxLTgwNDQtOWE2OTQ3ZGQ5Y2FkIiwgImVsZW1lbnQiOiAiZmllbGRfdXVpZCIsICJm
aWVsZF90eXBlIjogIl9fZnVuY3Rpb24iLCAic2hvd19pZiI6IG51bGwsICJzaG93X2xpbmtfaGVh
ZGVyIjogZmFsc2UsICJzdGVwX2xhYmVsIjogbnVsbH0sIHsiY29udGVudCI6ICIyMDY0YjZmYi1m
NGJmLTQzNTAtYjc5OC01OTRmNDNmMDI0NGMiLCAiZWxlbWVudCI6ICJmaWVsZF91dWlkIiwgImZp
ZWxkX3R5cGUiOiAiX19mdW5jdGlvbiIsICJzaG93X2lmIjogbnVsbCwgInNob3dfbGlua19oZWFk
ZXIiOiBmYWxzZSwgInN0ZXBfbGFiZWwiOiBudWxsfV0sICJ3b3JrZmxvd3MiOiBbXX1dLCAiZ2Vv
cyI6IG51bGwsICJncm91cHMiOiBudWxsLCAiaWQiOiAxMSwgImluYm91bmRfbWFpbGJveGVzIjog
bnVsbCwgImluY2lkZW50X2FydGlmYWN0X3R5cGVzIjogW10sICJpbmNpZGVudF90eXBlcyI6IFt7
InVwZGF0ZV9kYXRlIjogMTYwMjY0NTQyNjg3NCwgImNyZWF0ZV9kYXRlIjogMTYwMjY0NTQyNjg3
NCwgInV1aWQiOiAiYmZlZWMyZDQtMzc3MC0xMWU4LWFkMzktNGEwMDA0MDQ0YWEwIiwgImRlc2Ny
aXB0aW9uIjogIkN1c3RvbWl6YXRpb24gUGFja2FnZXMgKGludGVybmFsKSIsICJleHBvcnRfa2V5
IjogIkN1c3RvbWl6YXRpb24gUGFja2FnZXMgKGludGVybmFsKSIsICJuYW1lIjogIkN1c3RvbWl6
YXRpb24gUGFja2FnZXMgKGludGVybmFsKSIsICJlbmFibGVkIjogZmFsc2UsICJzeXN0ZW0iOiBm
YWxzZSwgInBhcmVudF9pZCI6IG51bGwsICJoaWRkZW4iOiBmYWxzZSwgImlkIjogMH1dLCAiaW5k
dXN0cmllcyI6IG51bGwsICJsYXlvdXRzIjogW10sICJsb2NhbGUiOiBudWxsLCAibWVzc2FnZV9k
ZXN0aW5hdGlvbnMiOiBbeyJhcGlfa2V5cyI6IFtdLCAiZGVzdGluYXRpb25fdHlwZSI6IDAsICJl
eHBlY3RfYWNrIjogdHJ1ZSwgImV4cG9ydF9rZXkiOiAiZm5fdGlvX2Fzc2V0cyIsICJuYW1lIjog
ImZuX3Rpb19hc3NldHMiLCAicHJvZ3JhbW1hdGljX25hbWUiOiAiZm5fdGlvX2Fzc2V0cyIsICJ0
YWdzIjogW10sICJ1c2VycyI6IFsicmVzYWRtaW5AbG9jYWwuY29tIl0sICJ1dWlkIjogImEyMmM3
YmQ1LTQwYzYtNGE1NC1iYmM3LTdkM2ZmMGY1MmFlMCJ9XSwgIm5vdGlmaWNhdGlvbnMiOiBudWxs
LCAib3ZlcnJpZGVzIjogW10sICJwaGFzZXMiOiBbXSwgInJlZ3VsYXRvcnMiOiBudWxsLCAicm9s
ZXMiOiBbXSwgInNjcmlwdHMiOiBbXSwgInNlcnZlcl92ZXJzaW9uIjogeyJidWlsZF9udW1iZXIi
OiA3MSwgIm1ham9yIjogMzgsICJtaW5vciI6IDEsICJ2ZXJzaW9uIjogIjM4LjEuNzEifSwgInRh
Z3MiOiBbXSwgInRhc2tfb3JkZXIiOiBbXSwgInRpbWVmcmFtZXMiOiBudWxsLCAidHlwZXMiOiBb
XSwgIndvcmtmbG93cyI6IFtdLCAid29ya3NwYWNlcyI6IFtdfQ==
""")
